#!/bin/bash

echo ""
echo "This script runs 'sudo chmod 666 /dev/spidev1.0 /dev/spidev1.1' "
echo "to facilitate bringing up the ST-Arm CANBUS connection."
echo ""

sudo chmod 666 /dev/spidev1.0 /dev/spidev1.1

echo ""
echo "Ready!"
echo ""